parameters:
#    noticias.example.class: DEPI\NoticiasBundle\Example

services:
#    noticias.example:
#        class: %noticias.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
