security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_ADMIN

    providers:
        administradores:
            memory:
                users:
                    sa: { password: 1234, roles: ROLE_ADMIN }

    firewalls:
        backend:
            pattern: ^/posgradmin
            provider: administradores
            http_basic: ~

    access_control:
        - { path: ^/posgradmin/*, roles: ROLE_ADMIN }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }