posgradoalumnos:
    pattern:  /posgradmin/posgradoalumnos
    defaults: { _controller: PosgradoAlumnosBundle:PosgradoAlumnos:index }

_posgradoalumnos:
    pattern: /posgradmin/posgradoalumnos/
    defaults: { _controller: FrameworkBundle:Redirect:redirect, route: posgradoalumnos}

posgradoalumnos_new:
    pattern:  /posgradmin/posgradoalumnos/new
    defaults: { _controller: PosgradoAlumnosBundle:PosgradoAlumnos:new }

posgradoalumnos_edit:
    pattern:  /posgradmin/posgradoalumnos/edit/{id}
    defaults: { _controller: PosgradoAlumnosBundle:PosgradoAlumnos:edit }

posgradoalumnos_create:
    pattern:  /posgradmin/posgradoalumnos/create
    defaults: { _controller: PosgradoAlumnosBundle:PosgradoAlumnos:create }

posgradoalumnos_update:
    pattern:  /posgradmin/posgradoalumnos/update/{id}
    defaults: { _controller: PosgradoAlumnosBundle:PosgradoAlumnos:update }

posgradoalumnos_delete:
    pattern:  /posgradmin/posgradoalumnos/delete/{id}
    defaults: { _controller: PosgradoAlumnosBundle:PosgradoAlumnos:delete }
